### ISSUE TITLE
登录成功之后无法获取imap服务器中的邮件

### ISSUE THREAD

**Issue by hkunzhe** [ooooevan/Vmail#1]
您好，我用的是QQ邮箱测试，应用程序返回一个花括号，如下图所示
![default](https://user-images.githubusercontent.com/30763967/37942942-136b6f30-31a8-11e8-9837-ee228a8e19c7.png)

**Comment by ooooevan** [comment]
已经登录成功了吗？点开一个邮件后这样的吗，请详细描述一下

**Comment by hkunzhe** [comment]
嗯，已经成功登录了，登录后主界面如下图
![default](https://user-images.githubusercontent.com/30763967/37943866-0a07cb06-31ac-11e8-8101-34cbe0342619.png)
收件箱中没有信息，点击刷新，就会出现下图的情况
![default](https://user-images.githubusercontent.com/30763967/37943911-3b6d0170-31ac-11e8-9bb0-c77a4240663f.png)
渲染进程的信息如下图所示
![default](https://user-images.githubusercontent.com/30763967/37943951-5ac405aa-31ac-11e8-99d9-119c6541e7b4.png)
主进程的信息如下图所示
![default](https://user-images.githubusercontent.com/30763967/37943975-78988c36-31ac-11e8-8f25-860236fe52ca.png)
本人刚接触electron不久，还希望您能解答下

**Comment by ooooevan** [comment]
这是获取邮件列表失败，alert的是err对象，它应该有值的。你能不能测试一下node-imap这个库里面的例子，看看是否报错

**Comment by hkunzhe** [comment]
应该是可以使用的，不过我在项目下执行`npm install`命令时，有如下警告出现
![default](https://user-images.githubusercontent.com/30763967/37946198-b5d6ce5a-31b6-11e8-989b-ea010ef9e0f8.png)
这个问题的出现是否和上面的警告有关
![default](https://user-images.githubusercontent.com/30763967/37946239-00922f48-31b7-11e8-811b-e887bb01a258.png)
这是我的node和npm的版本

**Comment by ooooevan** [comment]
暂时我也没想到什么原因，你打开控制台看看点菊花刷新，触发了哪些mutations，发给我看看。如果正确，应该有5个mutations
![image](https://user-images.githubusercontent.com/25603236/37947269-cb334502-31bc-11e8-8d18-df5cb7813fa1.png)

**Comment by ooooevan** [comment]
bug已修复，是path.join传参错误，要穿字符串，我误传number
