### ISSUE TITLE
[BUG] - 接收到的邮件正文中文内容，编码未能解析

### ISSUE THREAD

**Issue by lescpsn** [ooooevan/Vmail#2]
![qq 20180616020543](https://user-images.githubusercontent.com/24190375/41483008-0b81688c-710a-11e8-804d-9ce698bd786c.png)

**Comment by ooooevan** [comment]
我解析邮件主要是遇到一个解决一个，不能保证考虑到所有情况。这封邮件能发给我吗？或者发类型一样的。我分析一下。635638508@qq.com

**Comment by lescpsn** [comment]
在准备给你转发那个有显示问题的邮件之前，我本地用其他接收账号接收测试了下那封问题邮件的转发。
因为你目前的客户端上没有邮件转发功能，我只能用网页客户端打开那份显示有问题的邮件，但是显示是正常的，转发给我另外一个邮箱账户，再用你这个客户端显示就正常了，所以我猜测网页客户端对那封显示有问题的邮件进行了解码编码。可否在你现有的客户端上加个邮件转发功能，这样我就可以直接将问题邮件直接转发给你了。

**Comment by ooooevan** [comment]
转发的功能，它需要先解析出邮件内容，再将内容转发。如果解析就已经有问题了的话，转发后也是有问题的，并且无法知道问题在哪里，因为转发就丢失了`问题邮件`的源内容（邮件类型、邮件编码等）。要分析`问题邮件`，只能用原邮件内容来分析。
如果那封邮件是你发的，可以同样发一下给我。如果是别的网站发的，也可以教我怎么发，我想测试一下
