### ISSUE TITLE
[BUG] - 我先建立一个账号的时候，出现 该邮件太久 无法获取 的日志提示

### ISSUE THREAD

**Issue by lescpsn** [ooooevan/Vmail#3]
![qq 20180617213627](https://user-images.githubusercontent.com/24190375/41508663-dadb041e-727a-11e8-854d-426ed09b3db7.png)

**Comment by ooooevan** [comment]
是有这个问题，是`imap`库无法获取到邮件,我没有仔细研究是库的问题还是邮件服务器接口原因。只是发现较久远的邮件会这样，所以做了简单提示
