### ISSUE TITLE
[BUG] - 当有多个邮件接收人的时候，第二个收件人开始信息就显示不全了

### ISSUE THREAD

**Issue by lescpsn** [ooooevan/Vmail#4]
![qq 20180617220852](https://user-images.githubusercontent.com/24190375/41508731-c86797ba-727b-11e8-8fc3-905e9d604ff6.png)

**Comment by lescpsn** [comment]
![qq 20180617222404](https://user-images.githubusercontent.com/24190375/41508838-89c8d6a2-727d-11e8-8d11-71533708a94e.png)


这封邮件，两个接收账户以上的信息可以显示全

**Comment by ooooevan** [comment]
我是对字符串直接剪裁，显示固定长度的字符，鼠标移上去有title显示完整收件人信息。你要显示全部的话，找到然后把那行代码改一下就行了。
