### ISSUE TITLE
[BUG] - 查看邮件 -> 草稿箱 已保存的草稿箱，信息不能显示

### ISSUE THREAD

**Issue by lescpsn** [ooooevan/Vmail#6]
![qq 20180617223023](https://user-images.githubusercontent.com/24190375/41508888-2ec234f0-727e-11e8-9e4b-a8ceefc5b112.png)

**Comment by ooooevan** [comment]
对的，这个功能是没有的，我在文章有写，懒得写了。。功能应该是点击跳到写邮件页面，可以继续编辑邮件以发送。
